export const companiesHouse_ABI = {
  address: "0x",
  abi: [
    { type: "constructor", inputs: [], stateMutability: "nonpayable" },
    {
      type: "function",
      name: "DEFAULT_ADMIN_ROLE",
      inputs: [],
      outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "STAFF_ROLE",
      inputs: [],
      outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "companyBrief",
      inputs: [{ name: "companyId", type: "uint96", internalType: "uint96" }],
      outputs: [
        { name: "owner", type: "address", internalType: "address" },
        { name: "index", type: "uint96", internalType: "uint96" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "createCompany",
      inputs: [
        {
          name: "_creationParams",
          type: "tuple",
          internalType: "struct CompaniesHouseV1.CreateCompany",
          components: [
            { name: "name", type: "string", internalType: "string" },
            { name: "industry", type: "string", internalType: "string" },
            { name: "domain", type: "string", internalType: "string" },
            { name: "roles", type: "string[]", internalType: "string[]" },
            { name: "powerRoles", type: "string[]", internalType: "string[]" },
            { name: "ownerName", type: "string", internalType: "string" },
            { name: "ownerSalary", type: "uint256", internalType: "uint256" },
            { name: "ownerCurrency", type: "string", internalType: "string" },
          ],
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "creationFee",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "currentCompanyIndex",
      inputs: [],
      outputs: [{ name: "", type: "uint96", internalType: "uint96" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "dao",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "contract DAO" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "deleteCompany",
      inputs: [{ name: "_number", type: "uint96", internalType: "uint96" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "deletedCompanies",
      inputs: [],
      outputs: [{ name: "", type: "uint96", internalType: "uint96" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "employeeBrief",
      inputs: [
        { name: "employee", type: "address", internalType: "address" },
        { name: "companyId", type: "uint96", internalType: "uint96" },
      ],
      outputs: [
        { name: "isMember", type: "bool", internalType: "bool" },
        { name: "employeeIndex", type: "uint96", internalType: "uint96" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "fireEmployee",
      inputs: [
        { name: "_employeeAddress", type: "address", internalType: "address" },
        { name: "_companyId", type: "uint96", internalType: "uint96" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "getRoleAdmin",
      inputs: [{ name: "role", type: "bytes32", internalType: "bytes32" }],
      outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "grantRole",
      inputs: [
        { name: "role", type: "bytes32", internalType: "bytes32" },
        { name: "account", type: "address", internalType: "address" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "hasRole",
      inputs: [
        { name: "role", type: "bytes32", internalType: "bytes32" },
        { name: "account", type: "address", internalType: "address" },
      ],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "hireEmployee",
      inputs: [
        {
          name: "_hireParams",
          type: "tuple",
          internalType: "struct CompaniesHouseV1.HireEmployee",
          components: [
            {
              name: "employeeAddress",
              type: "address",
              internalType: "address",
            },
            { name: "name", type: "string", internalType: "string" },
            { name: "role", type: "string", internalType: "string" },
            { name: "companyId", type: "uint96", internalType: "uint96" },
            { name: "salary", type: "uint256", internalType: "uint256" },
            { name: "currency", type: "string", internalType: "string" },
          ],
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "initialize",
      inputs: [
        { name: "_token", type: "address", internalType: "address" },
        { name: "_treasuryAddress", type: "address", internalType: "address" },
        { name: "_daoAddress", type: "address", internalType: "address" },
        { name: "tokenSaleAddress", type: "address", internalType: "address" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "ownerToCompanies",
      inputs: [
        { name: "ownerAddress", type: "address", internalType: "address" },
        { name: "", type: "uint256", internalType: "uint256" },
      ],
      outputs: [
        { name: "companyId", type: "uint96", internalType: "uint96" },
        { name: "owner", type: "address", internalType: "address" },
        { name: "industry", type: "string", internalType: "string" },
        { name: "name", type: "string", internalType: "string" },
        { name: "createdAt", type: "uint256", internalType: "uint256" },
        { name: "active", type: "bool", internalType: "bool" },
        { name: "domain", type: "string", internalType: "string" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "payEmployee",
      inputs: [
        { name: "_employeeAddress", type: "address", internalType: "address" },
        { name: "_companyId", type: "uint96", internalType: "uint96" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "renounceRole",
      inputs: [
        { name: "role", type: "bytes32", internalType: "bytes32" },
        {
          name: "callerConfirmation",
          type: "address",
          internalType: "address",
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "retrieveCompany",
      inputs: [{ name: "_companyId", type: "uint96", internalType: "uint96" }],
      outputs: [
        {
          name: "",
          type: "tuple",
          internalType: "struct CompaniesHouseV1.CompanyStruct",
          components: [
            { name: "companyId", type: "uint96", internalType: "uint96" },
            { name: "owner", type: "address", internalType: "address" },
            { name: "industry", type: "string", internalType: "string" },
            { name: "name", type: "string", internalType: "string" },
            { name: "createdAt", type: "uint256", internalType: "uint256" },
            { name: "active", type: "bool", internalType: "bool" },
            {
              name: "employees",
              type: "tuple[]",
              internalType: "struct CompaniesHouseV1.Employee[]",
              components: [
                { name: "salary", type: "uint256", internalType: "uint256" },
                {
                  name: "lastPayDate",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "employeeId",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "payableAddress",
                  type: "address",
                  internalType: "address",
                },
                { name: "name", type: "string", internalType: "string" },
                { name: "companyId", type: "uint256", internalType: "uint256" },
                { name: "role", type: "string", internalType: "string" },
                { name: "hiredAt", type: "uint256", internalType: "uint256" },
                { name: "active", type: "bool", internalType: "bool" },
                { name: "currency", type: "string", internalType: "string" },
              ],
            },
            { name: "domain", type: "string", internalType: "string" },
            { name: "roles", type: "string[]", internalType: "string[]" },
            { name: "powerRoles", type: "string[]", internalType: "string[]" },
          ],
        },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "retrieveEmployee",
      inputs: [
        { name: "_companyId", type: "uint96", internalType: "uint96" },
        { name: "_employeeAddress", type: "address", internalType: "address" },
      ],
      outputs: [
        {
          name: "",
          type: "tuple",
          internalType: "struct CompaniesHouseV1.Employee",
          components: [
            { name: "salary", type: "uint256", internalType: "uint256" },
            { name: "lastPayDate", type: "uint256", internalType: "uint256" },
            { name: "employeeId", type: "address", internalType: "address" },
            {
              name: "payableAddress",
              type: "address",
              internalType: "address",
            },
            { name: "name", type: "string", internalType: "string" },
            { name: "companyId", type: "uint256", internalType: "uint256" },
            { name: "role", type: "string", internalType: "string" },
            { name: "hiredAt", type: "uint256", internalType: "uint256" },
            { name: "active", type: "bool", internalType: "bool" },
            { name: "currency", type: "string", internalType: "string" },
          ],
        },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "revokeRole",
      inputs: [
        { name: "role", type: "bytes32", internalType: "bytes32" },
        { name: "account", type: "address", internalType: "address" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "setCompanyRole",
      inputs: [
        { name: "_employeeAddress", type: "address", internalType: "address" },
        { name: "_newRole", type: "string", internalType: "string" },
        { name: "_companyId", type: "uint96", internalType: "uint96" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "supportsInterface",
      inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "tokenSale",
      inputs: [],
      outputs: [
        { name: "", type: "address", internalType: "contract TokenSale" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "treasury",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
  ],
};
